apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-tracker-app-deployment
  labels:
    app: payment-tracker-app

spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: payment-tracker-app

  template:
    metadata:
      labels:
        app: payment-tracker-app
    spec:
      containers:
        - name: payment-tracker-app
          image: bartee/payment-tracker-app:2.2.0
          ports:
            - containerPort: 8100
              name: http
