apiVersion: v1
kind: Service
metadata:
  name: payment-tracker-app
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: "payment-tracker"
  
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8100
  selector:
    app: payment-tracker-app
  type: LoadBalancer
