apiVersion: v1
kind: Secret
metadata:
  name: payment-tracker-api-secret
data:
  dbConnectionString: ##{DB_CONNECTION_STRING}##
  tokenSecret: ##{TOKEN_SECRET}##
  adminPassword: ##{ADMIN_PASSWORD}##
  appHost: ##{APP_HOST}##