name: 'Build'

jobs:
    - job: Build
      displayName: 'Build'
      variables:
        BuildConfiguration: Release
      workspace: 
        clean: all
      pool:
        name: Azure Pipelines
        vmImage: ubuntu-20.04
      steps:
      - task: qetza.replacetokens.replacetokens-task.replacetokens@3
        displayName: 'Replace tokens in **/appsettings.Production.config'
        inputs:
            rootDirectory: src
            targetFiles: '**/appsettings.Production.json'
            writeBOM: false
            tokenPrefix: '##{'
            tokenSuffix: '}##'

      - task: qetza.replacetokens.replacetokens-task.replacetokens@3
        displayName: 'Replace tokens in **/appsettings.Production.config'
        inputs:
            rootDirectory: src
            targetFiles: '**/environment.prod.ts'
            writeBOM: false
            tokenPrefix: '##{'
            tokenSuffix: '}##'

      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '5.0.x'           

      - script: './build.sh --target compile --configuration $(BuildConfiguration) --host AzurePipelines'
        displayName: 'Run NUKE build'

      - task: Docker@2
        displayName: Build API image
        inputs:
          repository: $(imageName)
          command: build
          buildContext: $(Build.SourcesDirectory)/src/api/Payment.Tracker/Payment.Tracker.Api/bin/$(BuildConfiguration)/net5.0
          Dockerfile: $(Build.SourcesDirectory)/src/api/Payment.Tracker/Payment.Tracker.Api/Dockerfile

      - task: Docker@2
        displayName: Publish API image
        inputs:
          containerRegistry: 'dockerhub-payment-tracker-api'
          repository: $(imageName)
          command: push        

      # - task: ArchiveFiles@2
      #   displayName: 'Archive API files'
      #   inputs:
      #       rootFolderOrFile: publish/api
      #       includeRootFolder: false
      #       archiveFile: '$(Build.ArtifactStagingDirectory)/Payment.Tracker.Api.zip'

      # - task: ArchiveFiles@2
      #   displayName: 'Archive APP files'
      #   inputs:
      #       rootFolderOrFile: publish/app
      #       includeRootFolder: false
      #       archiveFile: '$(Build.ArtifactStagingDirectory)/Payment.Tracker.App.zip'

      # - task: PublishBuildArtifacts@1
      #   displayName: 'Publish Artifacts'
      #   inputs:
      #     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      #     ArtifactName: Payment.Tracker
