// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Payment.Tracker.DataLayer;

namespace Payment.Tracker.DataLayer.Migrations
{
    [DbContext(typeof(PaymentContext))]
    [Migration("20210518151606_AddedTemplateSupport")]
    partial class AddedTemplateSupport
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Payment.Tracker.DataLayer.Models.PaymentPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("InvoiceReceived")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Paid")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PaymentSetId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentSetId");

                    b.ToTable("PaymentPositions");
                });

            modelBuilder.Entity("Payment.Tracker.DataLayer.Models.PaymentPositionTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("HasInvoice")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PaymentPositionTemplates");
                });

            modelBuilder.Entity("Payment.Tracker.DataLayer.Models.PaymentSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ForMonth")
                        .HasColumnType("date");

                    b.Property<bool>("InvoicesAttached")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("PaymentSets");
                });

            modelBuilder.Entity("Payment.Tracker.DataLayer.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Payment.Tracker.DataLayer.Models.PaymentPosition", b =>
                {
                    b.HasOne("Payment.Tracker.DataLayer.Models.PaymentSet", "PaymentSet")
                        .WithMany("PaymentPositions")
                        .HasForeignKey("PaymentSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentSet");
                });

            modelBuilder.Entity("Payment.Tracker.DataLayer.Models.PaymentSet", b =>
                {
                    b.Navigation("PaymentPositions");
                });
#pragma warning restore 612, 618
        }
    }
}
