version: '3.1'

services:
  payment-tracker-db:
    image: mysql:5.6
    restart: always
    container_name: payment-tracker-db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    ports:
      - 5555:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
